language: ruby
script: "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
env:
  - "CHECK=test"
  - "CHECK=rubocop"

matrix:
  exclude:
    - rvm: 1.9.3
      env: "CHECK=rubocop"
    - rvm: 1.8.7
      env: "CHECK=rubocop"
